[build]
buildCommand = "yarn && yarn preprocess && echo $VERIFYING_PAYMASTER_SIGNING_KEY > ./mnemonic.txt"

[deploy]
startCommand = "./run.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5